apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: poc-microservice-gateway
  namespace: development
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: poc-microservice-gateway-vsc
  namespace: development
spec:
  hosts:
  - "*"
  gateways:
  - poc-microservice-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: "development-gateway"
        port:
          number: 3000